# Netlify configuration for LUMINA Agricultural Suitability Analysis

[build]
  # No build process needed for static site
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # CORS headers for GeoTIFF files
  for = "/data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  # Redirect root to map page
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  # Handle SPA routing
  from = "/pages/*"
  to = "/pages/:splat"
  status = 200